### ISSUE TITLE
Ajouter le planning

### ISSUE THREAD

**Issue by maelchiotti** [StudioRvAndCo/CPM-frontend#110]
```[tasklist]
### Tasks
- [x] Utiliser Syncfusion Calendar
- [x] Afficher les séquences
- [ ] Rediriger vers une séquence quand tape dessus
```
