### ISSUE TITLE
Sign the APK with our own keys

### ISSUE THREAD

**Issue by maelchiotti** [StudioRvAndCo/CPM-frontend#83]
The release version of the APK needs to be signed with our own keys in the `build.gradle` file.

```[tasklist]
### Tasks
- [x] Create the signing keys
- [x] Sign the release APK
- [x] Add signing to the CI
```

```[tasklist]
### CI
- [x] Add the keystore file
- [x] Add the keys properties file
- [x] Inject files in the CI
- [x] Add documentation
```

**Comment by CoconutsX** [comment]
Told a colleague about this, she sent me this website: https://certbot.eff.org/
