### ISSUE TITLE
Améliorer le routage

### ISSUE THREAD

**Issue by maelchiotti** [StudioRvAndCo/CPM-frontend#85]
Utiliser [go_router](https://pub.dev/packages/go_router) pour gérer le routage.

```[tasklist]
### Tasks
- [x] Déclarer les routes
- [x] Utiliser les routes pour changer de page
```

```[tasklist]
### Utiliser les routes pour changer de page
- [x] Remplacer le système de widgets qui se remplacent dans la page Home par des routes
- [x] Utiliser les routes pour changer de page lors d'un clic sur le menu
```
