### ISSUE TITLE
Improve login code with a Form

### ISSUE THREAD

**Issue by maelchiotti** [StudioRvAndCo/CPM-frontend#95]
Improve the code of the login page with a [Form](https://docs.flutter.dev/cookbook/forms/validation), to prevent the user from leaving fields empty.

```[tasklist]
### Tasks
- [ ] Add a `Form` and `TextFormFields`
- [ ] Validate that fields are not empty
- [ ] Deactivate the login button if the fields are empty
```

**Comment by maelchiotti** [comment]
Closed because of https://github.com/StudioRvAndCo/CPM-frontend/issues/105
